project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
    - assignments.qmd
    - data.qmd
    - assignment1.qmd
    - assignment2.qmd
      
website:
  title: ""
  search: false  
  navbar:
    search: false
    title: MGMT 638
    file: index.qmd
    right:
      - text: Slides
        file: slides.qmd
      - text: Assignments
        file: assignments.qmd
      - text: Notebooks
        href: https://github.com/kerryback/mgmt638/tree/main/notebooks
      - text: Data
        file: data.qmd

    
format: 
  html:
    theme: cosmo
    scss: styles.css
    



