project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
    - notebooks.qmd
    - assignments.qmd
    - assignment1.qmd
    - assignment2.qmd
    - assignment3.qmd
    - assignment4.qmd
   
    
website:
  title: ""
  search: false  
  navbar:
    search: false
    title: MGMT 638

    right:
       
      - text: Code Binder
        href: https://mybinder.org/v2/gh/kerryback/2022-638-binder.git/HEAD

      - text: Slide Decks
        file: slides.qmd

      - text: Assignments
        file: assignments.qmd

      - text: Home
        file: index.qmd
    
format: 
  html:
    theme: cosmo
    scss: styles.css
    



